name: Sync Upstream Repository

on:
  schedule:
    - cron: '30 8 * * 0'  # 每小时执行一次，可以根据需要调整
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 步骤 1：检出你的仓库
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          ref: master  # 替换为你的实际分支名称
          fetch-depth: 0  # 拉取完整历史记录

      # 步骤 2：添加上游仓库
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/hanwckf/bl-mt798x.git
          git fetch upstream

      # 步骤 3：合并上游仓库的更新
      - name: Merge upstream changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git merge upstream/master --allow-unrelated-histories  # 替换为上游仓库的分支名称

      # 步骤 4：推送更新到你的仓库
      - name: Push changes to your repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token
        run: |
          git push origin master  # 替换为你的分支名称
